### ISSUE TITLE
Heroku deploy not connected to DB

### ISSUE THREAD

**Issue by JoshuaSkootsky** [The-Admirals-Emporium/have-yachts#111]
For bugs, please include the following:

* What is the expected behavior?

Should be able to log in

* What is the actual behavior?

Logging in doesn't work, get a "column "displayName" does not exist" error

* What steps reproduce the behavior?

Try logging in through local log in or OAuth.

For features, please specify at least minimal requirements, e.g.:

"As a user, I want to be able to log in"

Error displayed on logging in: ```"column "displayName" does not exist"```

**Comment by JoshuaSkootsky** [comment]
Okay. So. On localhost, we're fine after running npm run seed successfully.

But on Heroku, we don't have the db after deploying to Heroku. We don't have the boats or the log ins.
i.e.
[](https://have-yachts.herokuapp.com/boats)

**Comment by natiwhitney** [comment]
@JoshuaSkootsky 
have you tried to debug this on your own? What have you learned from your investigations?

We are a team here. If I notice a bug that is related to a part of the codebase that you or @amantina05 has worked on, I make a good faith effort to fix it myself. If I get stuck, or it seems like I am spending an unreasonable amount of time on it, then I post a bug request ticket indicating what I have looked at/what I have tried.

**Comment by JoshuaSkootsky** [comment]
Okay. This link works!

https://have-yachts.herokuapp.com/boats

Here's how I fixed it:

```
$ heroku run bash
Running bash on ⬢ have-yachts... up, run.8411 (Free)
~ $ npm run seed
```

and now the database is seeded and working as we expect.
