### ISSUE TITLE
Seed 10 yachts

### ISSUE THREAD

**Issue by JoshuaSkootsky** [The-Admirals-Emporium/have-yachts#12]
After the [boat schema](https://github.com/The-Admirals-Emporium/have-yachts/issues/17) is set up, 

Must first do #17

**Comment by natiwhitney** [comment]
As an engineer, I want to have a well-seeded database so that I am able to simulate a number of different scenarios for the user stories below.

**Comment by amantina05** [comment]
- By doing this, you really set yourselves up to tackle many of the points throughout the tiers. In the long run, this will save you, potentially, tons of time.
    - For example, seed hundreds of products with dummy data so that when you get to the "pagination" user story, you won't have to worry about adding more products.
    - Likewise, add a bunch of users with products in their carts so editing the cart can be worked on without already having the "add to cart" functionality built out.

**Comment by JoshuaSkootsky** [comment]
https://github.com/JoshuaSkootsky/junior-phase-final-project-2001/blob/master/seed.js
