### ISSUE TITLE
User Story: Rudiments of Security

### ISSUE THREAD

**Issue by natiwhitney** [The-Admirals-Emporium/have-yachts#16]
- [x] Protect our API (unauthorized user can't access routes)
- [x] Check permissions on back-end
- [x] Access controls
- [x] Properly authenticate user sessions

Resources:
https://learn.fullstackacademy.com/workshop/5abe5af280c4e100041a4ee6/content/5abe5af280c4e100041a4f0c/text

**Comment by natiwhitney** [comment]
Link to #14 

Link to #58

**Comment by JoshuaSkootsky** [comment]
#97 Made big progress to this User Story

**Comment by JoshuaSkootsky** [comment]
#102 I think closes this.
