### ISSUE TITLE
Create & Implement Database Schema Design

### ISSUE THREAD

**Issue by natiwhitney** [The-Admirals-Emporium/have-yachts#17]
Feature

"As a developer, I want to able to access user, boat, and orders"
---

- [x] Design schema for boats, users, orders
- [x] Create database models
- [x] Create Sequelize associations (boats & orders through order items; users & orders)

See schema design:
https://fullstackacademy.slack.com/files/US37P9U2W/FUD6Z0HMG/schema_design.md

**Comment by amantina05** [comment]
note for Tina: just validations & models

**Comment by JoshuaSkootsky** [comment]
I think this is still open until we have the Models.
