### ISSUE TITLE
Create accounts, Login & Logout

### ISSUE THREAD

**Issue by amantina05** [The-Admirals-Emporium/have-yachts#18]
---
- As a customer, I want to be able to create an account so I can have a logged-in experience

_Issue description here…_

-[] test login, logout 
-[] set up oAuth #9 
-[] education ourselves on how sessions are being handled
-[] persist user accounts in database

**Comment by JoshuaSkootsky** [comment]
Is #9 too vague? Or do we have it (#9) resolved already, but still need this ticket (#18) to implement the Google OAuth system we have working?
