### ISSUE TITLE
Show products to users

### ISSUE THREAD

**Issue by JoshuaSkootsky** [The-Admirals-Emporium/have-yachts#19]
Logged in or as a guest, a user can view all boats for sale.

This would be all boats in the Boats table.

A React component that, upon mounting, uses a Thunk creator to fetch from the DB the list of all boats, and displays the list of the boats.

Thunk => Redux Store => Boat state in the Redux store.

ComponentDidMount

connect from react-redux

**Comment by natiwhitney** [comment]
@JoshuaSkootsky see how i showed all robots in my jpfp
https://github.com/natiwhitney/junior-phase-final-project-2001

**Comment by JoshuaSkootsky** [comment]
Next thing to do is work on the redux store that will have the boats fetched from the database.

**Comment by JoshuaSkootsky** [comment]
I am able to fetch the boats from the Database, but I'm having trouble connecting my redux store to my display element.
