### ISSUE TITLE
User Story: Cart View/Add Boat to Cart

### ISSUE THREAD

**Issue by JoshuaSkootsky** [The-Admirals-Emporium/have-yachts#20]
### As a customer, I want to be able to add a product to my cart so I can collect my desired products in one place.

* Redux store (and later, database entity) that changes when a user adds a boat to their cart.

* It may be nice to provide the user the ability to view all the products in their card.

**Comment by natiwhitney** [comment]
Just access the cart via the NavBar

**Comment by natiwhitney** [comment]
Have to add quantities to cart 
- [ ] Boat list
- [ ] Cart view (cart state)
