### ISSUE TITLE
User Story: Validatation for fields in the Database

### ISSUE THREAD

**Issue by JoshuaSkootsky** [The-Admirals-Emporium/have-yachts#24]
* As an administrator, I want validated data so that it is reliable.
*  For example, each customer that creates an account should only be able to do so once with a single email address.
* Other reasonable validations, allowNull: false whenever reasonable
* No empty string when reasonable
* Other good validations, may have to edit seed file to reflect stricter controls on data

**Comment by JoshuaSkootsky** [comment]
Example: email address has the Unique column property from SQL

**Comment by natiwhitney** [comment]
@JoshuaSkootsky is there more work to do here ?

**Comment by natiwhitney** [comment]
From code review we will make some small adjustments based on notes

**Comment by natiwhitney** [comment]
- [ ] replace defaultValue in imageUrl with something sensible or nothing at all
- [ ] add bidirectional Order.belongsTo(User)
- [ ] rename OrderItems -> OrderBoats
- [ ] add inventory field to boats
- [ ] update attributes in single boat route -> only send what front-end is using
- [ ] Home route should route to home

**Comment by JoshuaSkootsky** [comment]
I vote this can be closed. Agree @natiwhitney @amantina05 ?

**Comment by amantina05** [comment]
agree
