### ISSUE TITLE
User Story: Only Admins Can Access DB through the front end

### ISSUE THREAD

**Issue by JoshuaSkootsky** [The-Admirals-Emporium/have-yachts#25]
- As an administrator and user, I want my data to be secure so that no one can unrightfully manipulate information.
 - Products are maintained (added, edited and removed) by administrators only.
 - All users can only be viewed by administrators.
 - Customers' carts/orders are only viewable/editable by themselves and administrators.

**Comment by JoshuaSkootsky** [comment]
* Only admin users can change the Database through the front end, except that customers can change our data that we store about their shopping cart and the orders that they create.

* Should be impossible for a non-admin to create or delete a boat. Our API for posting to Boats is going to need to be locked down to Admin users only.

**Comment by JoshuaSkootsky** [comment]
We should go in as engineers and make an Admin user in the database so that we can test Admin functionality. Can we put one admin in the seed file?

**Comment by natiwhitney** [comment]
@JoshuaSkootsky can you create an AllUsers view

**Comment by JoshuaSkootsky** [comment]
I think this is closed because the GET /users route is protected by isAdmin middleware.
