### ISSUE TITLE
User Story: Customers can checkout items in cart

### ISSUE THREAD

**Issue by amantina05** [The-Admirals-Emporium/have-yachts#26]
---
- As a customer, I want to be able to "checkout" the items in my cart so I can purchase my desired goods.
  - Think of a typical user experience on popular websites from a guest user and logged-in user perspective. 
    - You can just start with by simulating the experience of checking out with a simple confirmation page.

_Issue description here…_

- [ ]  checkout button

- [x] payment (tier 2)

- [ ]  persist shopping cart to database

- [ ] create a confirmation

**Comment by JoshuaSkootsky** [comment]
Cart becomes an order that we persist in the DB

**Comment by JoshuaSkootsky** [comment]
Tina did it! Tier 1 achieved. Tier 2 or three, we'll do this more for real.

**Comment by JoshuaSkootsky** [comment]
i.e. Tier 2, you checkout, order status in the DB changes.
