### ISSUE TITLE
User Story: Seed 100+ boats, orders, users

### ISSUE THREAD

**Issue by natiwhitney** [The-Admirals-Emporium/have-yachts#48]
For features, please specify at least minimal requirements, e.g.:

* "As a user, I want to see hundreds of boats"
---

- can use chrome API simplescraper.io to get images, descriptions, costs, and names of lots of boats
- add tests to seed-spec.js
- auto generate JSON
- [ ] paginate through boats #76

**Comment by JoshuaSkootsky** [comment]
See: https://news.ycombinator.com/item?id=21736288
[](https://blog.jooq.org/2016/08/10/why-most-programmers-get-pagination-wrong/)

**Comment by JoshuaSkootsky** [comment]
@natiwhitney @amantina05 can I have the 20 to 50 boats' data you scraped? I would like to use that real data (and pictures of real boats) for the seed file, and I'll generate many more products and names from that.

Tier 1 is hundreds of Boats. I will work on this seed filer after the Admin panel, over the weekend. If I finish both, I will say so in Slack.

**Comment by JoshuaSkootsky** [comment]
I talked with Jake and he said that we should add to our seed file if we need it to test more functionality.
