### ISSUE TITLE
Switch costs to Integers

### ISSUE THREAD

**Issue by natiwhitney** [The-Admirals-Emporium/have-yachts#57]
- [x] All costs should be represented on backend as integers (total, cost, historical)
- [ ] They should be converted to decimals by the routes
- [ ] They should be decimals on the front end

For features, please specify at least minimal requirements, e.g.:

* "As a front end developer, I want to use decimals rounded to two places"

---

_Issue description here…_

**Comment by natiwhitney** [comment]
Link to #24

**Comment by JoshuaSkootsky** [comment]
I am working on the routes.
They will display the cost in integers, divided by 100, rounded to 2 decimal places, as a string, in  $ USD
