### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by JoshuaSkootsky** [The-Admirals-Emporium/have-yachts#7]
### Deploy to Heroku

Get our Boilermaker project up on Heroku, no need for CI/CD yet, although that will be later

**Comment by amantina05** [comment]
- As an engineer, I want users to be able to access the website so they can browse and purchase our products.
  - (A deployed version of the website.)

**Comment by amantina05** [comment]
https://have-yachts.herokuapp.com/
