### ISSUE TITLE
Admin Display Panel is Visible to Admins

### ISSUE THREAD

**Issue by JoshuaSkootsky** [The-Admirals-Emporium/have-yachts#99]
Child of User Story #25 

There is an Admin Display Panel

It needs to be visible to admin users.

For this, I think we as developers should create in the seed file an admin user whose credentials we know, and use that to test the admin display panel.

Admin panel and functionality should not be available to non-Admins.

**Comment by JoshuaSkootsky** [comment]
This is testable from Cody being seeded in the Database in #100

**Comment by JoshuaSkootsky** [comment]
```
TIER 1: MVP Shopping Experience

- As an administrator and user, I want my data to be secure so that no one can unrightfully manipulate information.
  - Products are maintained (added, edited and removed) by administrators only.
  - All users can only be viewed by administrators.
  - Customers' carts/orders are only viewable/editable by themselves and administrators.
```

**Comment by natiwhitney** [comment]
@JoshuaSkootsky I have fixed aspects of the AdminPanel that were not working as expected on the master branch.

For example, in routes, admin panel was rendering for guest. And in NavBar it wasn't render for admins.

As a result, please take a look at the changes I have made on master to routes.js and navbar.js in anticipating that the PR with your changes may cause merge conflicts.

Let me know if you have any questions

**Comment by JoshuaSkootsky** [comment]
I have a branch that I was working on over the weekend.

https://github.com/The-Admirals-Emporium/have-yachts/tree/adminPanel

On this branch, the Nav Bar displays the link to the Admin panel only to logged in Admin users, but I have run into a blocker in terms of getting the Admin panel to display upon click to Admin users.

At our next stand up, I think I should either be assigned to keep working on this, or maybe someone could pair with me to help me get through this blocker.

**Comment by JoshuaSkootsky** [comment]
Update: this branch fails to build on Travis:

https://travis-ci.org/The-Admirals-Emporium/have-yachts/builds/660129005?utm_source=github_status&utm_medium=notification

**Comment by natiwhitney** [comment]
This needs to cover

- [ ] Products are maintained (added, edited and removed) by administrators only.
- [ ] All users can only be viewed by administrators.
- [ ] Customers' carts/orders are only viewable/editable by themselves and administrators.

**Comment by natiwhitney** [comment]
Issue for [adding routes for products](https://github.com/The-Admirals-Emporium/have-yachts/issues/114)
